<?php

namespace CjwPhpDesign\Src\Decorator;

/** 具体的装饰类
 * Class ConcreteDecoratorA
 * @package CjwPhpDesign\Src\Decorator
 */
class ConcreteDecoratorA extends DecoratorGeneral
{
    public function operation()
    {
        $this->addOperation();
        parent::operation(); // TODO: Change the autogenerated stub
    }

    public function addOperation()
    {
        echo "在装饰器前面进行修饰<br>";
    }
}